### ISSUE TITLE
Nach Installation kein DB-Update unter Contao 5.2.8

### ISSUE THREAD

**Issue by Anke** [BugBuster1701/contao-be_user_online-bundle#14]
Hallo Glen,

ich habe "Backend User Online" unter C5.2.8 (PHP 8.2) über den Contao Manager installiert. Die Installation funktionierte ohne Fehlermeldungen, aber es wurde kein Datenbankupdate durchgeführt, und das separate Installtool steht mir ja nicht mehr zur Verfügung.

Gruß,
Anke

**Comment by BugBuster1701** [comment]
Da ist die Anleitung leider nicht korrekt, es ist kein DB Update notwendig.
(Korrektur, siehe weiter unten)

**Comment by Anke** [comment]
Mir wird aber auch nach Cache-Leerungen und mehrmaligem Wiedereinloggen nichts angezeigt:

![2024-01-29_124618_be_user_online_2](https://github.com/BugBuster1701/contao-be_user_online-bundle/assets/1300920/e0113ce7-f1a5-4fac-b067-0f4bdc9d16c0)

**Comment by Anke** [comment]
Ah, auf der Detailseite ist es zu finden:

![2024-01-29_124618_be_user_online_3](https://github.com/BugBuster1701/contao-be_user_online-bundle/assets/1300920/0bb4abff-b7ab-48b5-91f0-15d39f135672)

**Comment by BugBuster1701** [comment]
Korrekur, Update ist eventuell doch nötig, da die Erweiterung contao-online-bundle als Abhängigkeit geladen wird und dieser braucht ein DB Udpate. (Tabelle tl_online_session)

Doch, das:
![grafik](https://github.com/BugBuster1701/contao-be_user_online-bundle/assets/1218809/87ffdca8-ab54-4832-85d1-9e5e7723cf4e)
Die Augen Icons sind dazu gekommen.

Die Spalte "Vorherige Anmeldung" bekommst du dazu, wenn du oben auf Sortierung das Feld auswählst und den Filter aktivierst.
![grafik](https://github.com/BugBuster1701/contao-be_user_online-bundle/assets/1218809/da11c7ce-a38d-466e-987a-eb0fa36b5715)

**Comment by Anke** [comment]
Okay, das mit der Sortierung muss man wissen. Bin es irgendwie (noch) so gewohnt, dass es immer in der Liste erschien.

Hatte eben noch einmal auf Aktualisieren (der Erweiterung) geklickt, aber ein DB-Update wurde trotzdem nicht durchgeführt.

**Comment by BugBuster1701** [comment]
Dann schaue mal ob die Tabelle `tl_online_session` bei dir vorhanden ist, wenn ja ist alles OK.

**Comment by Anke** [comment]
Ist vorhanden, Vielen Dank für deine Mühe!
