### ISSUE TITLE
Fehler bei Installation der Erweiterung

### ISSUE THREAD

**Issue by designpilot** [BugBuster1701/contao-be_user_online-bundle#5]
Hallo @BugBuster1701
Bei der Installation deiner Erweiterung bekomme ich auf einmal folgende Fehlermeldung ausgegeben:

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bugbuster/contao-be_user_online-bundle ^2.0 -> satisfiable by bugbuster/contao-be_user_online-bundle[2.0.0].
    - Conclusion: don't install contao-components/dropzone 4.3.0
    - bugbuster/contao-be_user_online-bundle 2.0.0 requires contao/core-bundle ~4.5 -> satisfiable by contao/core-bundle[4.5.0, 4.5.1, 4.5.10, 4.5.11, 4.5.12, 4.5.2, 4.5.3, 4.5.4, 4.5.5, 4.5.6, 4.5.7, 4.5.8, 4.5.9].
    - contao/core-bundle 4.5.0 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.1 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.10 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.11 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.12 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.2 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.3 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.4 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.5 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.6 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.7 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.8 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - contao/core-bundle 4.5.9 requires contao-components/dropzone ^5.0.1 -> satisfiable by contao-components/dropzone[5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.3.0, 5.3.1].
    - Can only install one of: contao-components/dropzone[5.0.1, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.1.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.1.1, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.2.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.3.0, 4.3.0].
    - Can only install one of: contao-components/dropzone[5.3.1, 4.3.0].
    - Installation request for contao-components/dropzone (locked at 4.3.0) -> satisfiable by contao-components/dropzone[4.3.0].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
Finished Composer Cloud resolving.`

Die Contao Installation ist eine frische CT 4.4.21 via Contao Manager 1.0.3 und bei anderen Installationen vorher CT 4.4.20 und tiefer hatte ich noch nie Probleme. Kannst Du mir da sagen wie das gelöst werden kann

**Comment by BugBuster1701** [comment]
Wie hier ja erläutert, liegt das an Composer bzw. die Art wie er die Erstinstallation eines Bundles behandelt. Nutzer muss wissen welche Version passt.
https://github.com/contao/contao-manager/issues/325

**Comment by BugBuster1701** [comment]
Ich werde für beide Versionen (1.0.x und 2.0.x) noch ein Update bringen, worin die Readme und Installationsbeschreibung angepasst werden.
