### ISSUE TITLE
warum nicht unter C4.4 installierbar?

### ISSUE THREAD

**Issue by zonky2** [BugBuster1701/contao-be_user_online-bundle#7]
https://github.com/BugBuster1701/contao-be_user_online-bundle/blob/master/composer.json#L24 ?

**Comment by BugBuster1701** [comment]
Ist es, dazu muss aber Version 1.0.x gewählt werden. Leider macht das Composer nicht automatisch.

**Comment by BugBuster1701** [comment]
Steht so übrigens auch in der Readme:

> Notice
>For Contao 4.3 or 4.4 please install version 1.x.y, for Contao 4.5 and later version 2.x.y.

**Comment by zonky2** [comment]
Weihnachten doch mal ne neue Brille für mich? :D
